// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: pkg/pb/order/order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductStockMinusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Stock int64 `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
}

func (x *ProductStockMinusRequest) Reset() {
	*x = ProductStockMinusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_order_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductStockMinusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductStockMinusRequest) ProtoMessage() {}

func (x *ProductStockMinusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_order_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductStockMinusRequest.ProtoReflect.Descriptor instead.
func (*ProductStockMinusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *ProductStockMinusRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ProductStockMinusRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type ProductStockMinusReponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *ProductStockMinusReponse) Reset() {
	*x = ProductStockMinusReponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_order_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductStockMinusReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductStockMinusReponse) ProtoMessage() {}

func (x *ProductStockMinusReponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_order_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductStockMinusReponse.ProtoReflect.Descriptor instead.
func (*ProductStockMinusReponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_order_order_proto_rawDescGZIP(), []int{1}
}

func (x *ProductStockMinusReponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_pb_order_order_proto protoreflect.FileDescriptor

var file_pkg_pb_order_order_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x22, 0x40, 0x0a, 0x18, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x63,
	0x6b, 0x4d, 0x69, 0x6e, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x22, 0x30, 0x0a, 0x18, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x4d, 0x69, 0x6e, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x60, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x57,
	0x0a, 0x11, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4d, 0x69,
	0x6e, 0x75, 0x73, 0x12, 0x1f, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4d, 0x69, 0x6e, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4d, 0x69, 0x6e, 0x75, 0x73, 0x52, 0x65,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x62, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pkg_pb_order_order_proto_rawDescOnce sync.Once
	file_pkg_pb_order_order_proto_rawDescData = file_pkg_pb_order_order_proto_rawDesc
)

func file_pkg_pb_order_order_proto_rawDescGZIP() []byte {
	file_pkg_pb_order_order_proto_rawDescOnce.Do(func() {
		file_pkg_pb_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_order_order_proto_rawDescData)
	})
	return file_pkg_pb_order_order_proto_rawDescData
}

var file_pkg_pb_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_pb_order_order_proto_goTypes = []interface{}{
	(*ProductStockMinusRequest)(nil), // 0: order.ProductStockMinusRequest
	(*ProductStockMinusReponse)(nil), // 1: order.ProductStockMinusReponse
}
var file_pkg_pb_order_order_proto_depIdxs = []int32{
	0, // 0: order.order.ProductStockMinus:input_type -> order.ProductStockMinusRequest
	1, // 1: order.order.ProductStockMinus:output_type -> order.ProductStockMinusReponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_pb_order_order_proto_init() }
func file_pkg_pb_order_order_proto_init() {
	if File_pkg_pb_order_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_order_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductStockMinusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_order_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductStockMinusReponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_order_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_order_order_proto_goTypes,
		DependencyIndexes: file_pkg_pb_order_order_proto_depIdxs,
		MessageInfos:      file_pkg_pb_order_order_proto_msgTypes,
	}.Build()
	File_pkg_pb_order_order_proto = out.File
	file_pkg_pb_order_order_proto_rawDesc = nil
	file_pkg_pb_order_order_proto_goTypes = nil
	file_pkg_pb_order_order_proto_depIdxs = nil
}
